apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: {{ .Values.namespace }}
  labels: 
    component: postgres
    
spec:
  selector:
    component: postgres
  ports:
    - port: {{ .Values.db.port }}
      targetPort: {{ .Values.db.port }}




