name: Build and Push Docker Images

on:
  push:
    branches:
      - 'master'
env:
  GKE_CLUSTER: staging-v3
  GKE_PROJECT: nodal-algebra-161404
  GKE_ZONE: us-west1-a
  IMAGE_NAME: demo-project

jobs:
  build-and-push-images:
    name: Docker Build and Push Images
    runs-on: ubuntu-latest

    env:
      IMAGE_TAG: ${{ github.ref }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build and Push Backend Docker Image
        run: |
          cd ./backend
          docker build -f Dockerfile -t eu.gcr.io/${env.GKE_PROJECT}/${env.IMAGE_NAME}:latest .

      - name: Confirm Image Builds and Pushes
        run: echo "All Docker images have been built and pushed successfully."
