name: Build and Push Docker Images

on:
  push:
    branches:
      - 'master'

jobs:
  build-and-push-images:
    name: Docker Build and Push Images
    runs-on: ubuntu-latest

    env:
      IMAGE_TAG: ${{ github.ref }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build and Push Backend Docker Image
        run: |
          cd ./backend
          docker build -f celeryworker.dockerfile -t eu.gcr.io/${GKE_PROJECT}/${IMAGE_NAME}-celeryworker:${IMAGE_TAG} .
      #     docker push eu.gcr.io/nodal-algebra-161404/backend:${{ github.ref }}

      # - name: Build and Push Celery Docker Image
      #   run: |
      #     cd celery
      #     docker build -t eu.gcr.io/nodal-algebra-161404/celery:${{ github.ref }} .
      #     docker push eu.gcr.io/nodal-algebra-161404/celery:${{ github.ref }}

      - name: Confirm Image Builds and Pushes
        run: echo "All Docker images have been built and pushed successfully."
