name: Build and Push Docker Images

# on:
#   repository_dispatch:
#     types: [staging]

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build-and-push-images:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build and Push Backend Docker Image
        run: |
          cd ./backend/app
          docker build -f Dockerfile -t eu.gcr.io/${{ env.GKE_PROJECT }}/backend:${{ github.event.release.tag_name }} .

      - name: Confirm Image Builds and Pushes
        run: echo "1st Docker images have been built and pushed successfully."

  build-and-push-images2:
    name: Build and Push Docker Images2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build and Push Backend Docker Image
        run: |
          cd ./backend/app
          docker build -f Dockerfile -t eu.gcr.io/${{ env.GKE_PROJECT }}/backend:${{ github.event.release.tag_name }} .

      - name: Confirm Image Builds and Pushes
        run: echo "2nd Docker images have been built and pushed successfully.....!"