name: Build Docker Image

on:
  push:
    tags:
      - '*'  # Trigger the workflow on tags that start with 'v'

jobs:
  build:
    name: Build and Push Docker Image to GCR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build -t gcr.io/nodal-algebra-161404/demo:${{ github.ref_name }} .

