# 


name: Create Release Tag

on:
  push:
    branches:
      - master

jobs:
  create-release-tag:
    name: Create Release Tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false
          token: ${{ secrets.PAT_TOKEN }}

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 20
          check-latest: true

      - name: Install Dependencies
        run: npm install -g semantic-release @semantic-release/github

      - name: Generate Release Tag
        id: create_release_tag
        run: npx semantic-release --debug --no-ci
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }} # Provide the token here
