name: Staging Release Tag

on:
  push:
    branches:
      - 'master'
      - 'OPS-2140-Docker-image-build'


permissions:
  contents: write
  pull-requests: write

jobs:
  create-release:
    name: Create Release for Tags
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Fetch Tags
        run: git fetch --tags 

      - name: Get Latest Stage Tag
        id: get_latest_tag
        run: |
          # Get the latest tag that ends with "-stage"
          latest_stage_tag=$(git tag --list '*-stage' | sort -V | tail -n 1)
          
          if [ -n "$latest_stage_tag" ]; then
            echo "Latest '-stage' tag: $latest_stage_tag"
            
            # Extract the tag number (remove the 'v' prefix)
            tag_number=$(echo "$latest_stage_tag" | sed 's/v//g' | sed 's/-stage//g')
            
            # Increment the tag number
            new_tag_number=$((tag_number + 1))
            
            # Construct the new tag
            new_tag="v$new_tag_number-stage"
          else
            # If no '-stage' tag is found, start with v1-stage
            new_tag="v1-stage"
          fi
        
          echo "New tag: $new_tag"
          
          # Create and push the new tag
          git tag $new_tag
          git push origin $new_tag
          
          # Set the new tag in the environment
          echo "new_tag=$new_tag" >> $GITHUB_ENV

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ env.new_tag }}  # Use the new incremented tag
          release_name: "${{ env.new_tag }}:${{ env.commit_message }}"  # Title of the release
        env:
          GITHUB_TOKEN: ${{ secrets.ARA_TOKEN }}  # Token for authentication

      - name: Trigger Docker Image Build Workflow
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.ARA_TOKEN }}
          event-type: build-image
          client-payload: '{"tag_name": "${{ env.new_tag }}"}'