name: Staging Release Tag

on:
  push:
    branches:
      - 'master'
      - 'OPS-2140-Docker-image-build'
permissions:
  contents: write
  pull-requests: write

jobs:
  create-release:
    name: Create Release for Tags
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Fetch Tags
        run: git fetch --tags 

      - name: Get Latest -stage Tag
        id: get_latest_tag
        run: |
          latest_tag=$(git describe --tags `git rev-list --tags --max-count=1` 2>/dev/null || echo "v102")
            echo "Latest tag: $latest_tag"
            
            # Extract the tag number (remove the 'v' prefix)
            tag_number=$(echo "$latest_tag" | sed 's/v//g')
            
            # Increment the tag number
            new_tag_number=$((tag_number + 1))
            
            # Construct the new tag
            new_tag="v$new_tag_number"
            echo "New tag: $new_tag"
            
            # Create and push the new tag
            git tag $new_tag
            git push origin $new_tag
            echo "new_tag=$new_tag" >> $GITHUB_ENV

      # - name: Create Release
      #   # id: create_release
      #   # uses: actions/create-release@v1
      #   uses: softprops/action-gh-release@v1
      #   with:
      #     name: ${{ env.new_tag }}-stage  # Title of the release
      #     tag_name: ${{ env.new_tag }}  # Use the new incremented tag
      #     token: ${{ secrets.NEW_PAT_TOKEN }}  # Token for authentication
      #     draft: false
      #     prerelease: false

      - name: release-please
        id: release
        uses: google-github-actions/release-please-action@v3
        with:
          release-type: simple
          package-name: release
          bump-minor-pre-major: true
          bump-patch-for-minor-pre-major: true
          token: ${{ secrets.NEW_PAT_TOKEN }}
          draft: false
          prerelease: false
