# 


name: Deploy action 
on:
  push:
    branches:
      - 'master'


jobs:
  deploy:
    name: Deploy git tag
    runs-on: ubuntu-latest
    steps:
      # To make git commits made by semantic-release be made to our bot and not "github-actions" user which doesn't trigger other Action Workflows. 
      # https://github.com/semantic-release/semantic-release/blob/2c30e268f9484adeb2b9d0bdf52c1cd909779d64/docs/recipes/ci-configurations/github-actions.md#pushing-packagejson-changes-to-a-master-branch
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          persist-credentials: false # <----- makes `github-actions` user account no longer push my commits. 
      - name: Deploy via semantic release 
        uses: cycjimmy/semantic-release-action@v2
        with: 
          semantic_version: 18
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}