# name: Create and Release Tag

# on:
#   push:
#     branches:
#       - 'main/branch'  
#   workflow_dispatch:
#     inputs:
#       release-tag-number:
#         description: 'Enter the release-tag number'
#         required: true

# jobs:
#   create-tag:
#     runs-on: ubuntu-latest
#     permissions:
#       contents: write
#       deployments: write

#     steps:
#       - name: Checkout Repository
#         uses: actions/checkout@v4

#       - name: Generate Release Tag
#         uses: ./
#         with:
#           release-tag-number: ${{ github.event.inputs.release-tag-number }}
#           user-email: ${{ secrets.USER_EMAIL }}
#           user-name: ${{ secrets.USER_NAME }}
#           github-token: ${{ secrets.GITHUB_TOKEN }}


name: Create Release

on:
  push:
    branches:
      - 'main/branch'
    tags:
      - 'v*'  # Trigger the workflow on tag pushes that start with 'v'

permissions:
  contents: write  # Required to create releases

jobs:
  release:
    name: Release pushed tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install GitHub CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y gh

      - name: Authenticate GitHub CLI
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

      - name: Create release
   
