# name: Create and Release Tag

# on:
#   push:
#     branches:
#       - 'main/branch'  
#   workflow_dispatch:
#     inputs:
#       release-tag-number:
#         description: 'Enter the release-tag number'
#         required: true

# jobs:
#   create-tag:
#     runs-on: ubuntu-latest
#     permissions:
#       contents: write
#       deployments: write

#     steps:
#       - name: Checkout Repository
#         uses: actions/checkout@v4

#       - name: Generate Release Tag
#         uses: ./
#         with:
#           release-tag-number: ${{ github.event.inputs.release-tag-number }}
#           user-email: ${{ secrets.USER_EMAIL }}
#           user-name: ${{ secrets.USER_NAME }}
#           github-token: ${{ secrets.GITHUB_TOKEN }}


name: Create and Release Tag

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:
    inputs:
      release-tag-number:
        description: 'Enter the release-tag number'
        required: true

jobs:
  create-tag:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      deployments: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Generate Release Tag
        uses: ./action.yaml
        with:
          release-tag-number: ${{ github.event.inputs.release-tag-number }}
          user-email: ${{ secrets.USER_EMAIL }}
          user-name: ${{ secrets.USER_NAME }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.event.inputs.release-tag-number }}
          release_name: Release ${{ github.event.inputs.release-tag-number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
