# name: Create and Release Tag

# on:
#   push:
#     branches:
#       - 'main/branch'  
#   workflow_dispatch:
#     inputs:
#       release-tag-number:
#         description: 'Enter the release-tag number'
#         required: true

# jobs:
#   create-tag:
#     runs-on: ubuntu-latest
#     permissions:
#       contents: write
#       deployments: write

#     steps:
#       - name: Checkout Repository
#         uses: actions/checkout@v4

#       - name: Generate Release Tag
#         uses: ./
#         with:
#           release-tag-number: ${{ github.event.inputs.release-tag-number }}
#           user-email: ${{ secrets.USER_EMAIL }}
#           user-name: ${{ secrets.USER_NAME }}
#           github-token: ${{ secrets.GITHUB_TOKEN }}


name: Create and Release Tag

on:
  push:
    branches:
      - 'main/branch'  # Trigger on pushes to 'main/branch'
    tags:
      - 'v*'  # Trigger on pushes to tags matching 'v*'

jobs:
  create-release:
    name: Create Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Token for creating the release
        with:
          tag_name: ${{ github.ref_name }}  # Use the tag name from the push event
          release_name: Release ${{ github.ref_name }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: false
          prerelease: false
