name: Create and Release Tag

on:
  workflow_dispatch:
    inputs:
      release-tag-number:
        description: 'Enter the release-tag number'
        required: true

jobs:
  create-tag:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      deployments: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Exit if the branch is not main
        run: |
          if [[ "${{ github.ref }}" != "refs/heads/main" ]]; then
            echo "Branch is not main, exiting."
            exit 1
          fi
        shell: bash

      # - name: Set Git Config
      #   run: |
      #     git config --global user.email "${{ secrets.USER_EMAIL }}"
      #     git config --global user.name "${{ secrets.USER_NAME }}"
      #   shell: bash

      - name: Generate Release Tag
        run: |
          echo "The input value is: ${{ github.event.inputs.release-tag-number }}"
          git tag -a ${{ github.event.inputs.release-tag-number }} -m "Updating tags"
          git push origin ${{ github.event.inputs.release-tag-number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash




# 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